### ISSUE TITLE
Details about the License

### ISSUE THREAD

**Issue by SunHaozhe** [justrajdeep/fonts#3]
Hello, 

Thanks for sharing the fonts. However, do you have more details about the License? 

I just found one single line in README. 

> GPLv2+, just like Mercurial.

I would like to know if I have the right to use these fonts for my research? Can I redistribute these fonts with my research project? If so, what are the obligations? 

Best regards,

**Comment by justrajdeep** [comment]
Hi @SunHaozhe 

Yes, you have the right to use these fonts for your research and can redistribute them freely.
If you make any modifications to the source code from this repo the resulting derivatives should be maximally published as open source ensuring software freedom.

Hope this helps

**Comment by SunHaozhe** [comment]
Hi @justrajdeep 

I do not plan to modify the source code from this repo, however, I am interested in using these ttf font files. My research project will be published as open source as soon as it's ready. In order to ensure the usability, I wish to redistribute the used ttf font files with my research project (if that does not violate copyrights). I believe that font files are always under strict copyright protection, so I prefer to fully clarify the situation to avoid any misunderstanding. 

Thanks a lot. 

Best regards,

**Comment by justrajdeep** [comment]
It does not violate the copyrights, you can redistribute freely. All the best with your research.
